/**
 * Single-file build.
 *
 *   node tools/build.mjs
 *
 * Produces dist/terminal-ballistics.html: the same application with every
 * module inlined, so it opens directly from disk with no server and no
 * network access. There is no external dependency and no minifier — the
 * output stays readable, which matters for a tool whose whole claim is that
 * the model is inspectable.
 *
 * The transform handles exactly the module syntax this codebase uses:
 * named imports, namespace imports, and `export` on function/class/const/let
 * declarations plus `export { ... }` lists. It refuses to guess: anything it
 * does not recognise is reported rather than silently dropped.
 */

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const ENTRY = resolve(ROOT, 'src/main.js');

const IMPORT_RE = /^[ \t]*import\s+(?:\{([\s\S]*?)\}|\*\s+as\s+([A-Za-z_$][\w$]*))\s+from\s+['"]([^'"]+)['"];?[ \t]*$/gm;
const BARE_IMPORT_RE = /^[ \t]*import\s+['"]([^'"]+)['"];?[ \t]*$/gm;

const modules = new Map();   // id -> { id, code, deps[] }
const order = [];
const visiting = new Set();

function idOf(abs) { return relative(ROOT, abs).split('\\').join('/'); }

function load(abs) {
  const id = idOf(abs);
  if (modules.has(id)) return id;
  if (visiting.has(id)) throw new Error(`circular import involving ${id}`);
  visiting.add(id);

  let src = readFileSync(abs, 'utf8');
  const deps = [];

  src = src.replace(BARE_IMPORT_RE, (m, spec) => {
    const dep = load(resolve(dirname(abs), spec));
    deps.push(dep);
    return `__req(${JSON.stringify(dep)});`;
  });

  src = src.replace(IMPORT_RE, (m, named, ns, spec) => {
    const dep = load(resolve(dirname(abs), spec));
    deps.push(dep);
    if (ns) return `const ${ns} = __req(${JSON.stringify(dep)});`;
    const parts = named.split(',').map((s) => s.trim()).filter(Boolean)
      .map((s) => {
        const mm = s.match(/^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$/);
        return mm ? `${mm[1]}: ${mm[2]}` : s;
      });
    return `const { ${parts.join(', ')} } = __req(${JSON.stringify(dep)});`;
  });

  const exported = new Set();

  // export { a, b };
  src = src.replace(/^[ \t]*export\s*\{([^}]*)\};?[ \t]*$/gm, (m, list) => {
    for (const s of list.split(',').map((x) => x.trim()).filter(Boolean)) {
      const mm = s.match(/^([A-Za-z_$][\w$]*)\s+as\s+([A-Za-z_$][\w$]*)$/);
      exported.add(mm ? `${mm[2]}: ${mm[1]}` : s);
    }
    return '';
  });

  // export function/class/const/let/var NAME
  src = src.replace(/^[ \t]*export\s+(async\s+)?(function\*?|class|const|let|var)\s+([A-Za-z_$][\w$]*)/gm,
    (m, asy, kind, name) => { exported.add(name); return m.replace(/^([ \t]*)export\s+/, '$1'); });

  const leftover = src.match(/^[ \t]*export\b.*$/gm);
  if (leftover) throw new Error(`${id}: unsupported export form -> ${leftover[0].trim()}`);

  const assign = exported.size
    ? `\n__exports.__all = {${[...exported].join(', ')}};\nObject.assign(__exports, __exports.__all);\ndelete __exports.__all;\n`
    : '';

  modules.set(id, { id, code: src + assign, deps });
  visiting.delete(id);
  order.push(id);
  return id;
}

const entryId = load(ENTRY);

const runtime = `
/* ============================================================================
 * Terminal Ballistics Sandbox — single-file build
 * Generated by tools/build.mjs. Source of truth is the src/ tree.
 * ========================================================================= */
(function () {
'use strict';
var __defs = {}, __cache = {};
function __def(id, fn) { __defs[id] = fn; }
function __req(id) {
  if (__cache[id]) return __cache[id];
  var m = __cache[id] = {};
  if (!__defs[id]) throw new Error('module not bundled: ' + id);
  __defs[id](m, __req);
  return m;
}
`;

let out = runtime;
for (const id of order) {
  const m = modules.get(id);
  out += `\n__def(${JSON.stringify(id)}, function (__exports, __req) {\n${m.code}\n});\n`;
}
out += `\n__req(${JSON.stringify(entryId)});\n})();\n`;

// ---- weave into the page ---------------------------------------------------
let html = readFileSync(resolve(ROOT, 'index.html'), 'utf8');
html = html.replace(/<script type="module">[\s\S]*?<\/script>\s*/, '');   // the file:// notice
html = html.replace(/<script type="module" src="\.\/src\/main\.js"><\/script>/,
  `<script>\n${out}\n</script>`);
html = html.replace('<title>', '<!-- single-file build: run tools/build.mjs to regenerate -->\n<title>');
html = html.replace('href="./docs/MODEL.md"', 'href="https://github.com/kvolio/kvo.1/blob/main/docs/MODEL.md"');

mkdirSync(resolve(ROOT, 'dist'), { recursive: true });
const target = resolve(ROOT, 'dist/terminal-ballistics.html');
writeFileSync(target, html);

console.log(`bundled ${modules.size} modules -> dist/terminal-ballistics.html `
  + `(${(html.length / 1024).toFixed(0)} kB)`);
